// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrBjfCCEc4bAWu861Udyolcd7TBti5IM4',
    appId: '1:149740829514:web:1404d82da1bc2f1d215fb3',
    messagingSenderId: '149740829514',
    projectId: 'chat-talk-db',
    authDomain: 'chat-talk-db.firebaseapp.com',
    storageBucket: 'chat-talk-db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuShMBiX1HtyCmghG-_hUuIXyczzTO_rU',
    appId: '1:149740829514:android:a370f4e4ecf85132215fb3',
    messagingSenderId: '149740829514',
    projectId: 'chat-talk-db',
    storageBucket: 'chat-talk-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxE8yT96hUnSY7CMnLCAX-E8bJJLAqHqg',
    appId: '1:149740829514:ios:2d92f668042313e0215fb3',
    messagingSenderId: '149740829514',
    projectId: 'chat-talk-db',
    storageBucket: 'chat-talk-db.appspot.com',
    iosBundleId: 'com.adtivemm.chatTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxE8yT96hUnSY7CMnLCAX-E8bJJLAqHqg',
    appId: '1:149740829514:ios:2d92f668042313e0215fb3',
    messagingSenderId: '149740829514',
    projectId: 'chat-talk-db',
    storageBucket: 'chat-talk-db.appspot.com',
    iosBundleId: 'com.adtivemm.chatTalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrBjfCCEc4bAWu861Udyolcd7TBti5IM4',
    appId: '1:149740829514:web:75990f4312d8e99a215fb3',
    messagingSenderId: '149740829514',
    projectId: 'chat-talk-db',
    authDomain: 'chat-talk-db.firebaseapp.com',
    storageBucket: 'chat-talk-db.appspot.com',
  );
}
